# Generated by Django 5.2.10 on 2026-02-16 17:05

from django.db import migrations


def create_demo_products(apps, schema_editor):
    Product = apps.get_model('adminapp', 'Product')

    if Product.objects.exists():
        return

    demo_products = [
        {
            "name": "Gaming Mouse",
            "price": 1499,
            "stock": 10,
            "description": "High precision gaming mouse"
        },
        {
            "name": "Mechanical Keyboard",
            "price": 3499,
            "stock": 5,
            "description": "RGB mechanical keyboard"
        },
        {
            "name": "Gaming Headset",
            "price": 2499,
            "stock": 8,
            "description": "Surround sound headset"
        },
        {
            "name": "Mouse Pad",
            "price": 499,
            "stock": 20,
            "description": "Large gaming mouse pad"
        },
        {
            "name": "Gaming Controller",
            "price": 2999,
            "stock": 6,
            "description": "Wireless gaming controller"
        },
    ]

    for product in demo_products:
        Product.objects.create(**product)


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_demo_products),
    ]
